<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f57fbbe1-45e7-4c05-85d2-1b087793a0b8</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ByteShop.Catalog.Application\ByteShop.Catalog.Application.csproj" />
    <ProjectReference Include="..\ByteShop.Catalog.Infrastructure\ByteShop.Catalog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
